-- Run this file in Supabase SQL Editor as the project database owner.
-- Additive migration: do NOT run schema.sql (it drops existing tables).
-- Payload: { "activeDraftId": "...", "drafts": [{ id, name, fieldValues, updatedAt }] }
-- Only server-side service_role may access these objects. No browser policies.
BEGIN;

CREATE OR REPLACE FUNCTION public.editor_backup_payload_valid(p_payload jsonb)
RETURNS boolean
LANGUAGE plpgsql IMMUTABLE SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
    v_draft jsonb;
    v_ids text[] := ARRAY[]::text[];
BEGIN
    IF p_payload IS NULL OR jsonb_typeof(p_payload) IS DISTINCT FROM 'object'
       OR octet_length(p_payload::text) > 2097152
       OR jsonb_typeof(p_payload->'activeDraftId') IS DISTINCT FROM 'string'
       OR jsonb_typeof(p_payload->'drafts') IS DISTINCT FROM 'array' THEN
        RETURN false;
    END IF;
    IF jsonb_array_length(p_payload->'drafts') NOT BETWEEN 1 AND 200 THEN
        RETURN false;
    END IF;
    FOR v_draft IN SELECT value FROM jsonb_array_elements(p_payload->'drafts') LOOP
        IF jsonb_typeof(v_draft) IS DISTINCT FROM 'object'
           OR jsonb_typeof(v_draft->'id') IS DISTINCT FROM 'string'
           OR length(v_draft->>'id') NOT BETWEEN 1 AND 200
           OR (v_draft->>'id') = ANY(v_ids)
           OR jsonb_typeof(v_draft->'name') IS DISTINCT FROM 'string'
           OR length(v_draft->>'name') NOT BETWEEN 1 AND 500
           OR jsonb_typeof(v_draft->'fieldValues') IS DISTINCT FROM 'object'
           OR jsonb_typeof(v_draft->'updatedAt') IS DISTINCT FROM 'string' THEN
            RETURN false;
        END IF;
        v_ids := array_append(v_ids, v_draft->>'id');
    END LOOP;
    RETURN (p_payload->>'activeDraftId') = ANY(v_ids);
END;
$$;

REVOKE ALL ON FUNCTION public.editor_backup_payload_valid(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.editor_backup_payload_valid(jsonb) TO service_role;

CREATE TABLE IF NOT EXISTS public.editor_backups (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    template_id bigint NOT NULL REFERENCES public.templates(id) ON DELETE CASCADE,
    -- SHA-256 hex of a random 32-byte token generated by the server.
    -- Never store the raw link token or return this hash to the browser.
    access_token_hash text NOT NULL CHECK (access_token_hash ~ '^[0-9a-f]{64}$'),
    payload jsonb NOT NULL CHECK (public.editor_backup_payload_valid(payload)),
    revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS editor_backups_template_id_idx ON public.editor_backups(template_id);

ALTER TABLE public.editor_backups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.editor_backups FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.editor_backups FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.editor_backups FROM service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.editor_backups TO service_role;

-- All editor saves (including an explicit OVERWRITE) must call this RPC.
-- On conflict, ask the user again. An OVERWRITE sends the revision the user
-- just reviewed; never bypass the comparison, even for a confirmed overwrite.
CREATE OR REPLACE FUNCTION public.save_editor_backup(
    p_backup_id uuid,
    p_template_id bigint,
    p_access_token_hash text,
    p_expected_revision bigint,
    p_payload jsonb
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
    v_backup public.editor_backups%ROWTYPE;
BEGIN
    -- The server derives this hash from the raw bearer token, never accepts
    -- a client-supplied hash. Wrong token and absent ID get the same response.
    SELECT b.* INTO v_backup FROM public.editor_backups AS b
    WHERE b.id = p_backup_id AND b.template_id = p_template_id
      AND b.access_token_hash = p_access_token_hash
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('status', 'not_found');
    END IF;
    IF p_expected_revision IS NULL OR p_expected_revision < 1 THEN
        RAISE EXCEPTION 'Expected revision must be a positive integer' USING ERRCODE = '22023';
    END IF;
    IF v_backup.revision <> p_expected_revision THEN
        RETURN jsonb_build_object('status', 'conflict', 'revision', v_backup.revision,
            'updatedAt', v_backup.updated_at);
    END IF;
    IF NOT public.editor_backup_payload_valid(p_payload) THEN
        RAISE EXCEPTION 'Invalid editor backup payload (maximum 2 MiB and 200 drafts)' USING ERRCODE = '22023';
    END IF;

    UPDATE public.editor_backups AS b
    SET payload = p_payload, revision = b.revision + 1, updated_at = clock_timestamp()
    WHERE b.id = v_backup.id
    RETURNING b.* INTO v_backup;

    RETURN jsonb_build_object('status', 'saved', 'id', v_backup.id,
        'revision', v_backup.revision, 'updatedAt', v_backup.updated_at);
END;
$$;

REVOKE ALL ON FUNCTION public.save_editor_backup(uuid, bigint, text, bigint, jsonb)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.save_editor_backup(uuid, bigint, text, bigint, jsonb)
    TO service_role;

COMMENT ON TABLE public.editor_backups IS
    'Private editor draft sets. Server-only access using a hashed link token; no user login required.';
NOTIFY pgrst, 'reload schema';
COMMIT;
