DROP TABLE IF EXISTS template_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS tag_groups;
DROP TABLE IF EXISTS templates;
DROP TABLE IF EXISTS creators;

-- ==========================================
-- 1. SHARED UPDATED_AT TRIGGER FUNCTION
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- ==========================================
-- 2. CREATORS TABLE
-- ==========================================
CREATE TABLE creators (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text NOT NULL,
  slug text UNIQUE,
  role text NOT NULL DEFAULT 'creator',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),

  CONSTRAINT creators_role_check CHECK (role IN ('owner', 'creator'))
);

CREATE TRIGGER update_creators_updated_at
  BEFORE UPDATE ON creators
  FOR EACH ROW
  EXECUTE PROCEDURE update_updated_at_column();

-- ==========================================
-- 3. TEMPLATES TABLE
-- ==========================================
CREATE TABLE templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  is_personal boolean DEFAULT false,
  password text,
  preview_url text,
  html_blueprint text,
  fields_config jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid REFERENCES auth.users(id)
);

CREATE TRIGGER update_templates_updated_at
  BEFORE UPDATE ON templates
  FOR EACH ROW
  EXECUTE PROCEDURE update_updated_at_column();

-- ==========================================
-- 4. TAG GROUPS TABLE
-- ==========================================
CREATE TABLE tag_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- ==========================================
-- 5. TAGS TABLE
-- ==========================================
CREATE TABLE tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint REFERENCES public.tag_groups(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  slug text UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now()
);

-- user_id meaning:
-- - NULL = global / owner-managed tag
-- - auth user id = creator-owned tag
-- The "creators" tag group can store one public creator tag per creator for side menu filtering.

-- ==========================================
-- 6. TEMPLATE_TAGS (Join Table)
-- ==========================================
CREATE TABLE template_tags (
  template_id bigint REFERENCES public.templates(id) ON DELETE CASCADE,
  tags_id bigint REFERENCES public.tags(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (template_id, tags_id)
);
